In [1]:
import pandas as pd

In [2]:
energyPrice_path = 'energyConsPricesNl2009.csv'
energyPriceNl = pd.read_csv(energyPrice_path, delimiter=';')

# Display column names for translation
energyPriceNl.columns.tolist()

['Prijscomponenten',
 'Belastingen',
 'Perioden',
 'Aardgasprijs/Verbruiksklassen huishoudens/Minder dan 569 m3 (euro per m3)',
 'Aardgasprijs/Verbruiksklassen huishoudens/569 tot 5 687 m3 (euro per m3)',
 'Aardgasprijs/Verbruiksklassen huishoudens/5 687 m3 en meer (euro per m3)',
 'Aardgasprijs/Verbruiksklassen niet-huishoudens/Minder dan 28 433 m3 (euro per m3)',
 'Aardgasprijs/Verbruiksklassen niet-huishoudens/28 433 tot 284 333 m3 (euro per m3)',
 'Aardgasprijs/Verbruiksklassen niet-huishoudens/284 333 tot 2 843 332 m3 (euro per m3)',
 'Aardgasprijs/Verbruiksklassen niet-huishoudens/2 843 332 tot 28 433 324 m3 (euro per m3)',
 'Aardgasprijs/Verbruiksklassen niet-huishoudens/28 433 324 m3 en meer (euro per m3)',
 'Elektriciteitsprijs /Verbruiksklassen huishoudens/Minder dan 1 MWh (euro per kWh)',
 'Elektriciteitsprijs /Verbruiksklassen huishoudens/1 tot 2,5 MWh (euro per kWh)',
 'Elektriciteitsprijs /Verbruiksklassen huishoudens/2,5 tot 5 MWh (euro per kWh)',
 'Elektriciteitsprijs /Verbruiksklassen huishoudens/5 tot 15 MWh (euro per kWh)',
 'Elektriciteitsprijs /Verbruiksklassen huishoudens/15 MWh en meer (euro per kWh)',
 'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/Minder dan 20 MWh (euro per kWh)',
 'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/20 tot 500 MWh (euro per kWh)',
 'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/500 tot 2 000 MWh (euro per kWh)',
 'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/2 000 tot 20 000 MWh (euro per kWh)',
 'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/20 000 tot 70 000 MWh (euro per kWh)',
 'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/70 000 tot 150 000 MWh (euro per kWh)',
 'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/150 000 MWh en meer (euro per kWh)']

In [3]:
# Mapping of Dutch column names to English translations
column_mapping = {
    'Prijscomponenten': 'Price_Components',
    'Belastingen': 'Taxes',
    'Perioden': 'Periods',
    'Aardgasprijs/Verbruiksklassen huishoudens/Minder dan 569 m3 (euro per m3)': 'NaturalGasPrice_Households_LessThan_569m3_EuroPerM3',
    'Aardgasprijs/Verbruiksklassen huishoudens/569 tot 5 687 m3 (euro per m3)': 'NaturalGasPrice_Households_569to5687m3_EuroPerM3',
    'Aardgasprijs/Verbruiksklassen huishoudens/5 687 m3 en meer (euro per m3)': 'NaturalGasPrice_Households_MoreThan_5687m3_EuroPerM3',
    'Aardgasprijs/Verbruiksklassen niet-huishoudens/Minder dan 28 433 m3 (euro per m3)': 'NaturalGasPrice_NonHouseholds_LessThan_28433m3_EuroPerM3',
    'Aardgasprijs/Verbruiksklassen niet-huishoudens/28 433 tot 284 333 m3 (euro per m3)': 'NaturalGasPrice_NonHouseholds_28433to284333m3_EuroPerM3',
    'Aardgasprijs/Verbruiksklassen niet-huishoudens/284 333 tot 2 843 332 m3 (euro per m3)': 'NaturalGasPrice_NonHouseholds_284333to2843332m3_EuroPerM3',
    'Aardgasprijs/Verbruiksklassen niet-huishoudens/2 843 332 tot 28 433 324 m3 (euro per m3)': 'NaturalGasPrice_NonHouseholds_2843332to28433324m3_EuroPerM3',
    'Aardgasprijs/Verbruiksklassen niet-huishoudens/28 433 324 m3 en meer (euro per m3)': 'NaturalGasPrice_NonHouseholds_MoreThan_28433324m3_EuroPerM3',
    'Elektriciteitsprijs /Verbruiksklassen huishoudens/Minder dan 1 MWh (euro per kWh)': 'ElectricityPrice_Households_LessThan_1MWh_EuroPerKWh',
    'Elektriciteitsprijs /Verbruiksklassen huishoudens/1 tot 2,5 MWh (euro per kWh)': 'ElectricityPrice_Households_1to2.5MWh_EuroPerKWh',
    'Elektriciteitsprijs /Verbruiksklassen huishoudens/2,5 tot 5 MWh (euro per kWh)': 'ElectricityPrice_Households_2.5to5MWh_EuroPerKWh',
    'Elektriciteitsprijs /Verbruiksklassen huishoudens/5 tot 15 MWh (euro per kWh)': 'ElectricityPrice_Households_5to15MWh_EuroPerKWh',
    'Elektriciteitsprijs /Verbruiksklassen huishoudens/15 MWh en meer (euro per kWh)': 'ElectricityPrice_Households_MoreThan_15MWh_EuroPerKWh',
    'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/Minder dan 20 MWh (euro per kWh)': 'ElectricityPrice_NonHouseholds_LessThan_20MWh_EuroPerKWh',
    'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/20 tot 500 MWh (euro per kWh)': 'ElectricityPrice_NonHouseholds_20to500MWh_EuroPerKWh',
    'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/500 tot 2 000 MWh (euro per kWh)': 'ElectricityPrice_NonHouseholds_500to2000MWh_EuroPerKWh',
    'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/2 000 tot 20 000 MWh (euro per kWh)': 'ElectricityPrice_NonHouseholds_2000to20000MWh_EuroPerKWh',
    'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/20 000 tot 70 000 MWh (euro per kWh)': 'ElectricityPrice_NonHouseholds_20000to70000MWh_EuroPerKWh',
    'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/70 000 tot 150 000 MWh (euro per kWh)': 'ElectricityPrice_NonHouseholds_70000to150000MWh_EuroPerKWh',
    'Elektriciteitsprijs /Verbruiksklassen niet-huishoudens/150 000 MWh en meer (euro per kWh)': 'ElectricityPrice_NonHouseholds_MoreThan_150000MWh_EuroPerKWh'
}

# Apply the column mapping to rename columns
energyPriceNl.rename(columns=column_mapping, inplace=True)

# Display the renamed columns
energyPriceNl.head()

,Price_Components,Taxes,Periods,NaturalGasPrice_Households_LessThan_569m3_EuroPerM3,NaturalGasPrice_Households_569to5687m3_EuroPerM3,NaturalGasPrice_Households_MoreThan_5687m3_EuroPerM3,NaturalGasPrice_NonHouseholds_LessThan_28433m3_EuroPerM3,NaturalGasPrice_NonHouseholds_28433to284333m3_EuroPerM3,NaturalGasPrice_NonHouseholds_284333to2843332m3_EuroPerM3,NaturalGasPrice_NonHouseholds_2843332to28433324m3_EuroPerM3,...,ElectricityPrice_Households_2.5to5MWh_EuroPerKWh,ElectricityPrice_Households_5to15MWh_EuroPerKWh,ElectricityPrice_Households_MoreThan_15MWh_EuroPerKWh,ElectricityPrice_NonHouseholds_LessThan_20MWh_EuroPerKWh,ElectricityPrice_NonHouseholds_20to500MWh_EuroPerKWh,ElectricityPrice_NonHouseholds_500to2000MWh_EuroPerKWh,ElectricityPrice_NonHouseholds_2000to20000MWh_EuroPerKWh,ElectricityPrice_NonHouseholds_20000to70000MWh_EuroPerKWh,ElectricityPrice_NonHouseholds_70000to150000MWh_EuroPerKWh,ElectricityPrice_NonHouseholds_MoreThan_150000MWh_EuroPerKWh
0,Totaalprijs,Inclusief btw en belastingen,2009 1e halfjaar,1.057,0.791,0.722,0.752,0.662,0.459,0.374,...,0.198,0.216,0.257,0.212,0.187,0.132,0.118,0.108,0.104,0.080
1,Totaalprijs,Inclusief btw en belastingen,2009 2e halfjaar,1.031,0.658,0.572,0.622,0.612,0.407,0.330,...,0.190,0.209,0.205,0.211,0.147,0.127,0.116,0.099,0.094,0.072
2,Totaalprijs,Inclusief btw en belastingen,2009,1.045,0.735,0.656,0.706,0.644,0.435,0.352,...,0.195,0.213,0.232,0.211,0.167,0.129,0.117,0.104,0.098,0.076
3,Totaalprijs,Inclusief btw en belastingen,2010 1e halfjaar,0.943,0.664,0.593,0.621,0.545,0.390,0.296,...,0.177,0.196,0.237,0.211,0.175,0.120,0.106,0.091,0.087,0.074
4,Totaalprijs,Inclusief btw en belastingen,2010 2e halfjaar,1.060,0.703,0.608,0.621,0.590,0.360,0.302,...,0.179,0.197,0.189,0.198,0.134,0.115,0.106,0.085,0.086,0.076

In [6]:
def preprocess_nao(path: str) -> pd.DataFrame:
    """
    Reset index, index is now the year and we want this as a column.
    Melt the dataset into a year, month and NAO column.
    Rename index to Year.
    Map the months (now strings) to corresponding month numbers.
    """
    nao = pd.read_csv(path, delim_whitespace=True, index_col=0)
    nao.reset_index(inplace=True)
    nao_melted = pd.melt(nao, id_vars=['index'], var_name='Month', value_name='NAO')
    nao_melted.rename(columns={'index':'Year'}, inplace=True)
    month_mapping = {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
                 'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12}
    nao_melted['Month'] = nao_melted['Month'].map(month_mapping)

    return nao_melted

In [7]:
NAO_file_path = 'NAO.txt'
nao = preprocess_nao(NAO_file_path)

In [8]:
nao

     Year  Month   NAO
0    1950      1  0.92
1    1951      1  0.08
2    1952      1  0.93
3    1953      1  0.33
4    1954      1  0.37
..    ...    ...   ...
895  2020     12 -0.30
896  2021     12  0.29
897  2022     12 -0.15
898  2023     12  1.94
899  2024     12  1.21

[900 rows x 3 columns]

In [10]:
def read_data(path: str) -> pd.DataFrame:
    """
    Read the data.
    Strip spaces from the columns.
    Rename all the columns (abbreviations -> full names).
    """

    weather = pd.read_csv(path)

    weather.columns = weather.columns.str.strip()
    weather = weather.applymap(lambda x: x.strip() if isinstance(x, str) else x)
    weather.replace('', None, inplace=True)

    column_mapping = {
        'YYYYMMDD': 'Date',
        'RH': 'DailyPrecipitation',
        'RHX': 'MaxHourlyPrecipitation',
        'RHXH': 'HDMaxPrecipitation',
        'TG': 'DailyMeanTemperature',
        'TN': 'HourlyMinTemperature',
        'TNH': 'HDMinTemperature',
        'TX': 'HourlyMaxTemperature',
        'TXH': 'HDMaxTemperature',
        'FG': 'DailyMeanWindspeed',
        'FHX': 'MaxHourlyMeanWindspeed',
        'FHXH': 'HDMaxMeanWindspeed',
        'FHN': 'MinHourlyMeanWindspeed',
        'FHNH': 'HDMinMeanWindspeed'
    }

    weather = weather[column_mapping.keys()]
    weather.rename(columns=column_mapping, inplace=True)

    return weather


def filter_on_year(weather: pd.DataFrame) -> pd.DataFrame:
    """
    Filter on only 2021 and later and reset index after filtering.
    """
    weather = weather[weather['Date'] >= 20210101]
    weather.reset_index(drop=True, inplace=True)

    return weather


def cast_datekey(weather: pd.DataFrame) -> pd.DataFrame:
    """
    Cast datekey 20210101 to format 2021/01/01
    """
    weather['Date'] = pd.to_datetime(weather['Date'], format='%Y%m%d').dt.strftime('%Y/%m/%d')

    return weather


def cast_hour_columns(weather: pd.DataFrame) -> pd.DataFrame:
    """
    Cast hour columns to integer.
    """
    hour_cols = [
        'HDMaxPrecipitation',
        'HDMinTemperature',
        'HDMaxTemperature',
        'HDMaxMeanWindspeed',
        'HDMinMeanWindspeed'
    ]

    for i in hour_cols:
        weather[i] = weather[i].astype(int)

    return weather


def convert_columns(weather: pd.DataFrame) -> pd.DataFrame:
    """
    Divide the following columns by 10 to get actual number, since they are 0.1 of the actual number.
    """
    cols_to_convert = [
        'DailyPrecipitation',
        'MaxHourlyPrecipitation',
        'DailyMeanTemperature',
        'HourlyMaxTemperature',
        'DailyMeanWindspeed',
        'MinHourlyMeanWindspeed',
        'MaxHourlyMeanWindspeed'
    ]
    for i in cols_to_convert:
        weather[i] = weather[i] / 10

    return weather


def create_date_columns(weather: pd.DataFrame) -> pd.DataFrame:
    """
    Cast date column (2021-01-01 instead of 2021/01/01) and add month and year columns
    Create a week key combining year and week number
    """
    weather['Date'] = pd.to_datetime(weather['Date'], format='%Y/%m/%d')
    weather['Month'] = weather['Date'].dt.month
    weather['Year'] = weather['Date'].dt.year
    weather['Week'] = weather['Date'].dt.isocalendar().week

    weather['WeekKey'] = weather['Year'].astype(str) + weather['Week'].apply(lambda x: '{:02d}'.format(x))
    weather['day_of_week'] = weather['Date'].dt.day_name()

    return weather


def preprocess_weather(path: str) -> pd.DataFrame:
    """
    Preprocess the weather data.
    """
    weather = read_data(path)
    weather = filter_on_year(weather)
    weather = cast_datekey(weather)
    weather = cast_hour_columns(weather)
    weather = convert_columns(weather)
    weather = create_date_columns(weather)

    return weather

In [11]:
weather_path = 'deBilt.csv'

weather = preprocess_weather(weather_path)

weather

C:\Users\duaaa\AppData\Local\Temp\ipykernel_3860\89597028.py:8: DtypeWarning: Columns (2,3,4,5,6,7,8,13,15,16,18,19,20,21,22,23,25,26,28,30,35,36,37,38,39,40) have mixed types. Specify dtype option on import or set low_memory=False.
  weather = pd.read_csv(path)

,Date,DailyPrecipitation,MaxHourlyPrecipitation,HDMaxPrecipitation,DailyMeanTemperature,HourlyMinTemperature,HDMinTemperature,HourlyMaxTemperature,HDMaxTemperature,DailyMeanWindspeed,MaxHourlyMeanWindspeed,HDMaxMeanWindspeed,MinHourlyMeanWindspeed,HDMinMeanWindspeed,Month,Year,Week,WeekKey,day_of_week
0,2021-01-01,0.0,0.0,1,3.0,-35,3,5.7,14,2.1,3.0,6,1.0,1,1,2021,53,202153,Friday
1,2021-01-02,0.3,0.1,9,3.6,31,8,4.5,1,1.8,3.0,1,1.0,14,1,2021,53,202153,Saturday
2,2021-01-03,0.1,0.1,23,3.3,28,7,4.0,14,3.5,5.0,15,2.0,1,1,2021,53,202153,Sunday
3,2021-01-04,1.1,0.6,3,2.8,23,23,3.6,10,5.3,6.0,10,5.0,1,1,2021,1,202101,Monday
4,2021-01-05,0.1,0.1,8,2.9,21,2,3.6,20,4.1,5.0,1,3.0,9,1,2021,1,202101,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,2025-01-11,-0.1,-0.1,1,0.5,-45,8,5.8,14,1.5,3.0,14,0.0,7,1,2025,2,202502,Saturday
1472,2025-01-12,0.1,0.1,21,1.7,-6,22,6.0,14,1.2,2.0,5,1.0,1,1,2025,2,202502,Sunday
1473,2025-01-13,0.0,0.0,1,0.5,-33,5,5.2,14,2.2,4.0,13,1.0,1,1,2025,3,202503,Monday
1474,2025-01-14,0.1,0.1,20,2.8,-16,1,5.7,24,3.1,5.0,13,2.0,6,1,2025,3,202503,Tuesday
1475,2025-01-15,0.0,0.0,1,6.6,56,1,7.3,17,1.2,2.0,1,0.0,19,1,2025,3,202503,Wednesday